# Generated by Django 5.0.3 on 2024-04-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_card_carditems'),
        ('pruduct', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pruduct.coupon'),
        ),
    ]
